###
POST http://localhost:3000/api/v1/worker/new-worker HTTP/1.1
Content-Type: application/json

{
    "firstname": "juan",
    "lastname": "Andres",
    "document_number": "3",
    "type_document": "cedula",
    "work": [{
        "id_work": "3",
        "name_work": "carnicero"
    }]
}

###
GET http://localhost:3000/api/v1/worker/ HTTP/1.1

###
GET http://localhost:3000/api/v1/worker/651b1fd8666a319dd423bda6 HTTP/1.1

###
PATCH  http://localhost:3000/api/v1/worker/651b1fd8666a319dd423bda6 HTTP/1.1
Content-Type: application/json

{
    "work": [{
        "id_work": "4",
        "name_work": "Arquitecto"
    }]
}

###
DELETE  http://localhost:3000/api/v1/worker/651b210ac96036a6aba2bc9c HTTP/1.1

